### ISSUE TITLE
Kermit's Review

### ISSUE THREAD

**Issue by defoebrand** [Amita-Roy/global-summit-2020#1]
General
> Great project
> Stacks nicely
> Vertical "Global Summit" at widest screen is a nice touch
> Push more button to branch
> Title of Homepage says "Document"
> Needs links
> Needs space between Featured Speakers and text - on About page
> Spinning globe is a nice touch

**Comment by amita-roy** [comment]
Thanks for helping me to improve my project. I have made all the changes as per your feedback hence closing the issue.
